server:
  port: ${APP_PORT:9090}
  servlet:
    context-path: /theta
  compression:
    enabled: true
    min-response-size: 1024
  forward-headers-strategy : framework

spring:
  banner:
    location: classpath:banner.txt
  profiles:
    active: ${PROFILE:local,dev}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost:3306}/${DATABASE_NAME:theta_liquibase}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE:2}
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
  liquibase:
    enabled: ${DATABASE_MIGRATION:true}
    change-log: classpath:db/db.changelog.yaml

application:
  configuration:
    cors-allowed-list:
      -  http://localhost:6555
      -  ${PORTAL_URL:http://localhost:8080}
      -  ${API_URL:http://localhost:9090}
    public-api-list:
      - /api/public/**

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %thread ${PID} [%X{correlationId}] %-5level %logger{36} - %class{1} - %msg%n"